Updated veiler build script names

diff --git a/Veiler b/Veiler
--- a/Veiler
+++ b/Veiler
@@ -4,7 +4,6 @@ PKGREPO="https://ilovetrees242.github.io/DevHelp/Website/Packages/"
 VEILERTESTS=0
 VEILERQUIET=0
 VEILERDOC=0
-USETOOLS=0
 YELLOW='\033[1;33m'
 ORANGE='\033[0;33m'
 WHITE='\033[1;37m'
@@ -13,7 +12,8 @@ DARKGRAY='\033[1;30m'
 NC='\033[0m'
 
 PROCESSID=""
-CURRENTPWD=""
+PREVUSERPWD=""
+VEILERARGS=""
 
 package_check(){
     if [ $(id -u) != 0 ]; then
@@ -27,32 +27,49 @@ package_check(){
         printf "\r${ORANGE}Checking if required packages are installed on your computer...${NC}"; sleep 0.2
     done &
     PROCESSID=$!
-    for PACKAGE in find wget awk gcc make patch grep tar readelf; do
+    for PACKAGE in find bash wget awk gcc make patch grep tar readelf; do
         $PACKAGE --version 1&> /dev/null 
         if [ $? -eq 127 ]; then
             echo -e "${YELLOW}$PACKAGE is not installed on your system! Veiler will use prebuilt binaries from the tool directory.${NC}"
             PATH=$PATH:/usr/lib/Veiler/Tools/usr/bin/
-            USETOOLS=1
         fi
+        sleep 0.1
     done && kill $PROCESSID && printf "\n${YELLOW}Done!${NC}\n"     
 }
+clean(){
+    rm -rf /var/cache/Veiler/*
+}
 parse_options(){
-    for((i=0; i < $#; i++)){
-        case $1 in
+    for(( i=1; i <= $#; i++ )){
+        case ${!i} in
             --quiet)
-                VEILERQUIET=1
-                echo -e "${GRAY}Quiet mode enabled.${NC}"
+                if [ $VEILERQUIET -eq 0 ]; then
+                    set -- ${@:1:$((i-1))} ${@:$((i+1))}
+                    VEILERQUIET=1
+                    i=0
+                elif [ $VEILERQUIET -eq 1 ]; then
+                    echo -e "${Yellow}Quiet mode already enabled!${NC}"; exit 1
+                fi
             ;;
             --documentation)
-                VEILERDOC=1
-                echo -e "${GRAY}Documentation enabled.${NC}"
+                if [ $VEILERDOC -eq 0 ]; 
+                    set -- ${@:1:$((i-1))} ${@:$((i+1))}
+                    VEILERDOC=1
+                    i=0
+                elif [ $VEILERDOC -eq 1 ]; then
+                    echo -e "${YELLOW}Documentation already enabled!${NC}"; exit 1
+                fi
             ;;
-            --test)
-                VEILERTESTS=1
-                echo -e "${GRAY}Tests enabled.${NC}"
+            --tests)
+                if [ $VEILERTESTS -eq 0 ]; then
+                    set -- ${@:1:$((i-1))} ${@:$((i+1))}
+                    VEILERTESTS=1
+                    i=0
+                elif [ $VEILERTESTS -eq 1 ]; then
+                    echo -e "${YELLOW}Tests are already enabled!${NC}"; exit 1
+                fi
             ;;
         esac
-        shift
     }
 }
 case $1 in
@@ -65,21 +82,69 @@ case $1 in
         fi
         shift 
         echo "Args: $@"
-        for(( i=0; i < $#; i++ )){
-            case $1 in 
-                --quiet)
-                    shift
-                ;;
-                --verbose)
-                    shift
-                ;;
-                --documentation)
-                    shift
-                ;;
-            esac
-            if [ $VEILERQUIET -ne 1 ]; then
+        if [ $VEILERQUIET -eq 0 ]; then
+            if [ $# -ge 2 ]; then
+                VEILERARGS=$@
+                for(( i=0; i < $#; i++ )){
+                    echo -e "${YELLOW}Changing directory to /var/cache/Veiler...${NC}"
+                    cd /var/cache/Veiler && clean
+                    PREVUSERPWD=$PWD
+                    echo -e "${YELLOW}Checking if packages exist...${NC}"
+                    wget $PKGREPO$1.tar.gz 
+                    if [ $? -eq 0 ]; then
+                        echo -e "${YELLOW}->Package ${WHITE}$1${YELLOW} found${NC}"
+                    elif [ $? -eq 8 ]; then
+                        echo -e "${YELLOW}->Package ${ORANGE}$1${YELLOW} not found!${NC}"
+                        exit 1
+                    else
+                        echo -e "${YELLOW}->An unknown error occured while fetching the packages.${NC}"
+                        exit 1
+                    fi
+                }
+                set -- $VEILERARGS
+                # TO DO: loop for extracting and building each package one by one
+                    # xxx
+            else
+                echo -e "${YELLOW}Changing directory to /var/cache/Veiler...${NC}"
+                PREVUSERPWD=$PWD
+                cd /var/cache/Veiler && clean
                 echo -e "${ORANGE}Checking if package ${YELLOW}$1${ORANGE} exists...${NC}"
                 wget "$PKGREPO$1.tar.gz" 
+                case $? in 
+                    8)
+                        echo -e "${YELLOW}Package ${ORANGE}$1${YELLOW}not found!${NC}"
+                        exit 1
+                    ;;
+                    0)
+                        echo -e "\n${ORANGE}Package ${WHITE}$1${ORANGE}found!${NC}"
+				        echo -e "${YELLOW}Installing ${WHITE}$1${YELLOW} in${NC}"
+				        for i in 1 2 3 4 5 ; do
+                            printf "${WHITE}%d${NC}" "$i"
+					        for j in 1 2 3; do
+                                sleep 0.1
+                                printf "${YELLOW}.${NC}"
+                            done
+                            sleep 1
+				        done
+                        echo
+                        echo -e "${YELLOW}Extracting the build tarball...${NC}"
+                        tar xvf $1.tar.gz
+                        pushd $1
+                            source ./MOONBUILD build && source ./MOONBUILD install
+                        popd
+                        cd $PREVUSERPWD
+                    ;;
+                    *)
+                        echo -e "${YELLOW}An unknown error was encountered while downloading the build tarball.${NC}"
+                        cd $PREVUSERPWD
+                        exit 1
+                    ;;
+                esac
+            fi
+        elif [ $VEILERQUIET -eq 1 ]; then
+            if [ $# -ge 2 ]; then
+                # TO DO: Add commands for fetching and building multiple packages
+                echo "$@"
             else
                 while true; do
                     echo -ne "\r${ORANGE}Checking if package ${YELLOW}$1${ORANGE} exists   ${NC}"; sleep 0.2; 
@@ -88,50 +153,47 @@ case $1 in
                     echo -ne "\r${ORANGE}Checking if package ${YELLOW}$1${ORANGE} exists...${NC}"; sleep 0.2; 
                 done &
                 PROCESSID=$!
-	    	    wget "$PKGREPO$1.tar.gz" &> /dev/null && kill $PROCESSID && echo
-            fi
-	    	case $? in
-		    	8)
-			    	echo -e "${YELLOW}Package ${ORANGE}$1${YELLOW}not found!${NC}"
-                ;;
-			    0)  
-                    echo -e "\n${ORANGE}Package ${WHITE}$1${WHITE}found!${NC}"
-				    echo -e "${YELLOW}Installing ${WHITE}$1${YELLOW} in${NC}"
-				    for i in 1 2 3 4 5 ; do
-                        printf "${WHITE}%d${NC}" "$i"
-					    for j in 1 2 3; do
-                            sleep 0.1
-                            printf "${YELLOW}.${NC}"
-                        done
-                        sleep 1
-				    done
-                    echo
-                    if [ $VEILERQUIET -eq 1 ]; then
+	    	    wget "$PKGREPO$1.tar.gz" &> /dev/null && kill $PROCESSID 
+                case $? in
+		    	    8)
+			    	    echo -e "${YELLOW}Package ${ORANGE}$1${YELLOW}not found!${NC}"
+                        exit 1
+                    ;;
+			        0)  
+                        echo -e "\n${ORANGE}Package ${WHITE}$1${WHITE} found!${NC}"
+				        echo -e "${YELLOW}Installing ${WHITE}$1${YELLOW} in${NC}"
+				        for i in 1 2 3 4 5 ; do
+                            printf "${WHITE}%d${NC}" "$i"
+					        for j in 1 2 3; do
+                                sleep 0.1
+                                printf "${YELLOW}.${NC}"
+                            done
+                            sleep 1
+				        done
+                        echo
                         while true; do
                             echo -ne "\r${ORANGE}Extracting the build tarball   ${NC}"; sleep 0.2; 
                             echo -ne "\r${ORANGE}Extracting the build tarball.  ${NC}"; sleep 0.2; 
                             echo -ne "\r${ORANGE}Extracting the build tarball.. ${NC}"; sleep 0.2; 
                             echo -ne "\r${ORANGE}Extracting the build tarball...${NC}"; sleep 0.2; 
                         done &
-                        tar xf $1.tar.gz && kill $! && echo -e "\n${YELLOW}Successfully extracted $1.tar.gz;${NC}"; echo
-                    else
-				        wget $PKGREPO/$1.tar.gz
-				        tar xvf $1.tar.gz
+                        tar xf $1.tar.gz && kill $! && echo -e "\n${YELLOW}->Successfully extracted $1.tar.gz;${NC}"; echo
                         if [ $? -ne 0 ]; then
                             echo "${YELLOW}An error was encountered while extracting the build tarball.${NC}"
+                            exit 1
+                        else
+		    		        pushd "$1"
+			    	            source ./LFSBUILD uninstall
+				            popd 
                         fi
-                    fi
-		    		pushd $1
-			    	    source ./LFSBUILD build
-				    popd 
-				;;
-                *)
-                    echo -e "${YELLOW}An unknown error occured. Manual intervention is required. Please use verbose mode and inspect the package manager script manually.${NC}"
-                    exit 1
-                ;;
-		    esac
-            shift
-        }
+				    ;;
+                    *)
+                        echo -e "${YELLOW}An unknown error occured. Manual intervention is required. Please use verbose mode and inspect the package manager script manually.${NC}"
+                        exit 1
+                    ;;
+		        esac
+            fi
+        fi
     ;;
 	veil)
         parse_options $@
@@ -143,27 +205,21 @@ case $1 in
         shift
         for(( i=0; i < $#; i++ )){
             case $1 in 
-                --quiet)
-                    shift
-                ;;
-                --verbose)
-                    shift
-                ;;
-                --documentation)
-                    shift
-                ;;
+                --quiet) shift ;;
+                --verbose) shift ;;
+                --documentation) shift ;;
             esac
             if [ "$VEILERQUIET" -eq 1 ]; then
                 if [ $# -ge 2 ]; then
                     echo "\033[s"
                     while true; do
-                        echo -ne "\r${ORANGE}Checking if packages exist   ${NC}"; sleep 0.2
-                        echo -ne "\r${ORANGE}Checking if packages exist.  ${NC}"
-                        echo -ne "\r${ORANGE}Checking if packages exist.. ${NC}"
-                        echo -ne "\r${ORANGE}Checking if packages exist...${NC}"
+                        echo -ne "\r${ORANGE}Checking if packages exist   ${NC}"; sleep 0.2; echo "\033[u"
+                        echo -ne "\r${ORANGE}Checking if packages exist.  ${NC}"; sleep 0.2; echo "\033[u"
+                        echo -ne "\r${ORANGE}Checking if packages exist.. ${NC}"; sleep 0.2; echo "\033[u"
+                        echo -ne "\r${ORANGE}Checking if packages exist...${NC}"; sleep 0.2; echo "\033[u"
                     done &
                     PROCESSID=$!
-                    wget "$PKGREPO$1.tar.gz" &> /dev/null
+                    wget "$PKGREPO$1.tar.gz" &> /dev/null 
                     if [ $? -eq 8 ]; then
                         echo -e "${YELLOW}Package $1 not found!${NC}"
                     elif [ $? -eq 0 ]; then
@@ -173,18 +229,20 @@ case $1 in
                     fi
                 else
                     while true; do
-		                echo -ne "\r${ORANGE}Checking if the package ${YELLOW}$2${ORANGE} exists   ${NC}"; sleep 0.2
-		                echo -ne "\r${ORANGE}Checking if the package ${YELLOW}$2${ORANGE} exists.  ${NC}"; sleep 0.2
-		                echo -ne "\r${ORANGE}Checking if the package ${YELLOW}$2${ORANGE} exists.. ${NC}"; sleep 0.2
-		                echo -ne "\r${ORANGE}Checking if the package ${YELLOW}$2${ORANGE} exists...${NC}"; sleep 0.2
+		                echo -ne "\r${ORANGE}Checking if the package ${YELLOW}$1${ORANGE} exists   ${NC}"; sleep 0.2
+		                echo -ne "\r${ORANGE}Checking if the package ${YELLOW}$1${ORANGE} exists.  ${NC}"; sleep 0.2
+		                echo -ne "\r${ORANGE}Checking if the package ${YELLOW}$1${ORANGE} exists.. ${NC}"; sleep 0.2
+		                echo -ne "\r${ORANGE}Checking if the package ${YELLOW}$1${ORANGE} exists...${NC}"; sleep 0.2
                     done &
                     PROCESSID=$!
-		            wget "$PKGREPO$1.tar.gz" &> /dev/null
+		            wget "$PKGREPO$1.tar.gz" &> /dev/null && kill $PROCESSID && echo
 		            case $? in
 			        8)
 				        echo -e "${YELLOW}Package ${WHITE}$1${WHITE}does not exist!${NC}"
 		    	    ;;
                     0)
+                        echo -e "\n${ORANGE}Package ${WHITE}$1${WHITE} found!${NC}"
+				        echo -e "${YELLOW}Uninstalling ${WHITE}$1${YELLOW} in${NC}"
 			            for i in 1 2 3 4 5 ; do
                             printf "${WHITE}%d${NC}" "$i"
 			                for j in 1 2 3; do
@@ -194,10 +252,17 @@ case $1 in
                             sleep 1
 			            done
                         echo
-				        tar xf $1.tar.gz
+                        while true; do
+                            echo -ne "\r${ORANGE}Extracting the build tarball   ${NC}"; sleep 0.2
+                            echo -ne "\r${ORANGE}Extracting the build tarball.  ${NC}"; sleep 0.2
+                            echo -ne "\r${ORANGE}Extracting the build tarball.. ${NC}"; sleep 0.2
+                            echo -ne "\r${ORANGE}Extracting the build tarball...${NC}"; sleep 0.2
+                        done &
+                        PROCESSID=$!
+				        tar xf "$1.tar.gz" && kill $PROCESSID && echo -e "${YELLOW}->Successfully extracted $1.tar.gz${NC}"
                  
-					    pushd $1
-					        source ./LFSBUILD uninstall
+					    pushd "$1"
+					        source ./MOONBUILD uninstall
 					    popd
 				    ;;
                     *)
@@ -212,14 +277,14 @@ case $1 in
         }
 	;;
 	strengthen)
-		
+        parse_options $@
 	;;
 	help)
 		echo -e "${WHITE}$0 Usage: $0 <OPTIONS> <COMMAND>${NC}"
 		echo -e "${WHITE}$0 unveil|veil <OPTIONS> [PACKAGE]${NC}"
 		echo -e "${WHITE}$0 Options:" 
 	   echo -e "${GRAY}--verbose${NC}${WHITE} : Displays verbose output"
-      	   echo -e "${GRAY}--quiet${NC}${WHITE} : Displays quiet output, not too detailed."
+       echo -e "${GRAY}--quiet${NC}${WHITE} : Displays quiet output, not too detailed."
 	   echo -e "${GRAY}--documentation${NC}${WHITE} : Enables documentation (this might install extra dependencies)"
 	   echo -e "${GRAY}--test${NC}${WHITE}: Enables test harnesses" 
 		echo -e "${WHITE}$0 unveil: Installs a package from source.${NC}"
@@ -230,7 +295,7 @@ case $1 in
 		
 	;;
     version)
-            
+            echo -e "Veiler development version. V"
     ;;
 	*)
         echo -e "${RED}Invalid action specified!${NC}"
