added much cooler messages, some minor optimizations and completed size estimation

diff --git a/Veiler b/Veiler
--- a/Veiler
+++ b/Veiler
@@ -7,6 +7,8 @@ VEILERQUIET=0
 VEILERDOC=0
 VEILERASK=0
 VEILERSKIPDESC=0
+DARKBLUE='\033[0;34m'
+BLUE='\033[1;34m'
 YELLOW='\033[1;33m'
 ORANGE='\033[0;33m'
 WHITE='\033[1;37m'
@@ -166,15 +168,11 @@ case $1 in
                     fi
                 done < "/var/db/Veiler/sync/$PACKAGE/dependencies"
             done
-            for((i=0; i < ${#PACKAGEBUFFER[@]}; i++)){
-                PACKAGEBUFFER[$i]=""
-            }
+            PACKAGEBUFFER=()
             for((i=0; i < ${#DEPSBUFFER[@]}; i++)){
                 PACKAGEBUFFER[$i]=${DEPSBUFFER[$i]}
             }
-            for((i=0; i < ${#DEPSBUFFER[@]}; i++)){
-                DEPSBUFFER[$i]=""
-            }
+            DEPSBUFFER=()
             DEPBUFCNTR=0
         done
         checkifexists(){
@@ -185,11 +183,11 @@ case $1 in
             }
             echo "no"
         }
-        for((i=0; i < ${#DEPS[@]}; i++)){
-            PACKAGES[${#PACKAGES[@]}]=${DEPS[$i]}
-        }
         for((i=0; i < ${#PACKAGES[@]}; i++)){
             PACKAGEBUFFER[$i]=${PACKAGES[$i]}
+        }
+        for((i=0; i < ${#DEPS[@]}; i++)){
+            PACKAGEBUFFER[${#PACKAGEBUFFER[@]}]=${DEPS[$i]}
         }
         for((i=0; i < ${#PACKAGEBUFFER[@]}; i++)){
             EXISTS=$(checkifexists ${PACKAGEBUFFER[$i]})
@@ -206,30 +204,27 @@ case $1 in
                 BUFFER=$(echo $BUFFER | sed "s@$PACKAGE@@1")
             }
         done
-        for((i=0; i < ${#PACKAGES[@]}; i++)){
-            PACKAGES[$i]=""
-        }
-        for((i=0; i < ${#BUFFER[@]}; i++)){
-            PACKAGES[$i]=${BUFFER[$i]}
-        }
-        veiler_stop_animation
         # Reverse the packages to build in correct order
-        PACKAGES=( $(printf "%s\n" "${PACKAGES[@]}" | tac) )
+        PACKAGES=( $BUFFER )
+        PACKAGES=( $(printf "%s\n" ${PACKAGES[@]} | tac) )
         set -- ${PACKAGES[@]}
+        veiler_stop_animation
         for((i=1; i <= $#; i++)){
             PKGVERSION[$((i-1))]="$(sed -n 's/^MOONPKGVERSION=//; s/"$//; s/^"//p' /var/db/Veiler/sync/"${!i}"/info)"
             PKGNAME[$((i-1))]="$(sed -n 's/^MOONPKGNAME=//; s/"$//; s/^"//p' /var/db/Veiler/sync/"${!i}"/info)"
             ((COUNT++))
         }
-        echo -ne "${YELLOW}Packages to be installed: ${NC}"
+        echo -ne "\n${YELLOW}Packages to be installed: ${NC}"
         for((i=0; i < $#; i++)){
             if [ -d /var/db/Veiler/local/"${PKGNAME[$i]}" ]; then
                 LOCALPKGVERSION="$(sed -n 's/^MOONPKGVERSION=//; s/"$//; s/^"//p' /var/db/Veiler/local/"${PKGNAME[$i]}"/info)"
-            fi
-            if [ "${PKGVERSION[$i]}" != "$LOCALPKGVERSION" ]; then
-                echo -ne "${WHITE}"${PKGNAME[$i]}" ${GRAY}("$LOCALPKGVERSION")${WHITE} -> "${PKGNAME[$i]}" ${GRAY}("${PKGVERSION[$i]}")${NC}   "
+                if [ "${PKGVERSION[$i]}" != "$LOCALPKGVERSION" ]; then
+                    echo -ne "${WHITE}"${PKGNAME[$i]}" ${GRAY}("$LOCALPKGVERSION")${WHITE} -> "${PKGNAME[$i]}" ${GRAY}("${PKGVERSION[$i]}")${NC}   "
+                else
+                    echo -ne "${WHITE}"${PKGNAME[$i]}" ${GRAY}("$LOCALPKGVERSION")${NC}  "
+                fi
             else
-                echo -ne "${WHITE}"${PKGNAME[$i]}" ${GRAY}("$LOCALPKGVERSION")${NC}  "
+                echo -ne "${WHITE}"${PKGNAME[$i]}" ${GRAY}("${PKGVERSION[$i]}")${NC}  "
             fi
         }
         echo; echo
@@ -237,20 +232,37 @@ case $1 in
             SPACEBUFFER=$(sed -n 's/^REQDSKSPC=//p' /var/db/Veiler/sync/$PACKAGE/info)
             SPACEBUFFER="$(echo $SPACEBUFFER | sed 's/"//g')"
             ((TOTALDSR+=SPACEBUFFER))
-        echo $TOTALDSR
         done
+        ((TOTALDSR/=1000))
+        echo -e "${DARKBLUE}*** ${BLUE}Total disk space required: ${WHITE}"$TOTALDSR"KiB${NC}"
         for PACKAGE in $@; do
             SPACEBUFFER=$(sed -n 's/^DOWNLOADSIZE=//p' /var/db/Veiler/sync/$PACKAGE/info)
             SPACEBUFFER="$(echo $SPACEBUFFER | sed 's/"//g')"
-            ((TOTAL+=SPACEBUFFER))
+            ((TOTALDOWNLOADSIZE+=SPACEBUFFER))
         done
+        ((TOTALDOWNLOADSIZE/=1000))
+        echo -e "${DARKBLUE}*** ${BLUE}Total download size: ${WHITE}"$TOTALDOWNLOADSIZE"KiB${NC}"
+        for PACKAGE in $@; do
+            SPACEBUFFER=$(sed -n 's/^INSTALLEDSIZE=//p' /var/db/Veiler/sync/$PACKAGE/info)
+            SPACEBUFFER="$(echo $SPACEBUFFER | sed 's/"//g')"
+            ((TOTALINSTSIZE+=SPACEBUFFER))
+        done
+        ((TOTALINSTSIZE/=1000))
+        echo -e "${DARKBLUE}*** ${BLUE}Total installed size: ${WHITE}"$TOTALINSTSIZE"KiB${NC}"
+        for PACKAGE in $@; do
+            SPACEBUFFER=$(sed -n 's/^WODOCINSTALLEDSIZE=//p' /var/db/Veiler/sync/$PACKAGE/info)
+            SPACEBUFFER="$(echo $SPACEBUFFER | sed 's/"//g')"
+            ((WODOCINSTSIZE+=SPACEBUFFER))
+        done
+        ((WODOCINSTSIZE/=1000))
+        echo -e "${DARKBLUE}*** ${BLUE}Total installed size ( without documentation ): ${WHITE}"$WODOCINSTSIZE"KiB${NC}"
         if [ "$VEILERASK" -eq 1 ]; then
             echo -ne "${YELLOW}||| ${WHITE}Proceed with the installation?[y/n]: "
             read -n 1
             if [ "$REPLY" == "y" ]; then
                 echo; true
             else
-                echo; exit 0
+                echo -e "${NC}"; exit 0
             fi
         fi
         if [ $VEILERQUIET -eq 0 ]; then
@@ -269,30 +281,41 @@ case $1 in
             }
             echo -e "${YELLOW}Important: ${WHITE}Extracting the package build tarballs...${NC}"
             for((i=0; i < $#; i++)){
-                echo -e "${YELLOW}($((i+1))/$#) Extracting ${PKGNAME[$i]}: ${WHITE}"
+                echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Extracting >>> ${WHITE}${PKGNAME[$i]}"
                 tar xf "build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}".tar.gz"
                 if [ $? -ne 0 ]; then
-                    echo -e "${ORANGE}Error: ${WHITE}Could not extract the build tarball for ${YELLOW}${PKGNAME[$i]}${NC}"; exit 1
+                    echo -e "${ORANGE}Error: ${WHITE}Could not extract the build tarball for ${YELLOW}${PKGNAME[$i]} ${GRAY}($((i+1))/$#) ${NC}"; exit 1
                 fi
-            }; exit 1
+            }
+            echo -e "${YELLOW}Important: ${WHITE}Downloading sources...${NC}"
             for((i=0; i < $#; i++)){
                 pushd "build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}"" &> /dev/null
                     source ./MOONBUILD getpkg
+                    if [ $? -ne 0 ]; then
+                        echo -e "${ORANGE}Error: ${WHITE}Failed to download the source for ${PKGNAME[$i]} ${GRAY}($((i+1))/$#)${NC}"
+                    fi
                 popd &> /dev/null
             }
             for((i=0; i < $#; i++)){
-                echo -ne "\r${WHITE}(${GRAY}"$((i+1))"/"$#"${WHITE}) ${YELLOW}Important: ${WHITE}Verifying package integrity ||| ${PKGNAME[$i]}                 "
+                echo -ne "\r${WHITE}(${GRAY}"$((i+1))"/"$#"${WHITE}) ${YELLOW}Important: ${WHITE}Verifying package integrity ||| ${PKGNAME[$i]}                                     "
                 pushd "build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}"" &> /dev/null
                     source ./MOONBUILD verifyintegrity
+                    if [ $? -ne 0 ]; then
+                        echo -e "${ORANGE}Error: ${WHITE}Failed to verify package integrity for package: ${PKGNAME[$i]} ${GRAY}$((i+1)) ${WHITE}of ${GRAY}$# ${NC}"
+                        exit 1
+                    fi
                 popd &> /dev/null
                 tar -cf "build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}".tar.gz" "build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}"" 
             }; echo
             for((i=0; i < $#; i++)){
                 Package="build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}""
                 pushd $Package 
+                    echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Building ${WHITE}>>> ${PKGNAME[$i]}${NC}"
                     source ./MOONBUILD build
+                    echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Installing ${WHITE}>>> ${PKGNAME[$i]}${NC}"
                     source ./MOONBUILD install
                 popd
+                echo -e "${GRAY}($((i+1))/$#)${YELLOW}Completed build${WHITE} >>> ${PKGNAME[$i]}${NC}"
                 rm -rf $Package
             }
             popd
@@ -310,33 +333,45 @@ case $1 in
                     fi
                 fi
             }
-            play_animation "${YELLOW}Important: ${WHITE}Extracting the package build tarballs...${NC}"
+            echo -e "${YELLOW}Important: ${WHITE}Extracting the package build tarballs...${NC}"
             for((i=0; i < $#; i++)){
+                echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Extracting >>> ${WHITE}${PKGNAME[$i]}"
                 tar xf "build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}".tar.gz"
                 if [ $? -ne 0 ]; then
                     veiler_stop_animation
-                    echo -e "${ORANGE}Error: ${WHITE}Could not extract the build tarball for ${YELLOW}${PKGNAME[$i]}${NC}"; exit 1
+                    echo -e "${ORANGE}Error: ${WHITE}Could not extract the build tarball for ${YELLOW}${PKGNAME[$i]} ${GRAY}($((i+1))/$#)${NC}"; exit 1
                 fi
             }
             veiler_stop_animation
+            echo -e "${YELLOW}Important: ${WHITE}Downloading sources...${NC}"
             for((i=0; i < $#; i++)){
                 pushd "build-${PKGNAME[$i]}-${PKGVERSION[$i]}" &> /dev/null 
                     source ./MOONBUILD getpkg
+                    if [ $? -ne 0 ]; then
+                        echo -e "${ORANGE}Error: ${WHITE}Failed to download the source for ${PKGNAME[$i]} ${GRAY}($((i+1))/$#)${NC}"
+                    fi
                 popd &> /dev/null
             }
             for((i=0; i < $#; i++)){
                 echo -ne "\r${WHITE}(${GRAY}"$((i+1))"/"$#"${WHITE}) ${YELLOW}Important: ${WHITE}Verifying package integrity ||| ${PKGNAME[$i]}                 "
                 pushd "build-${PKGNAME[$i]}-${PKGVERSION[$i]}" &> /dev/null 
                     source ./MOONBUILD verifyintegrity
+                    if [ $? -ne 0 ]; then
+                        echo -e "${ORANGE}Error: ${WHITE}Failed to verify package integrity for package for ${PKGNAME[$i]} ${GRAY}$((i+1)) ${WHITE}of ${GRAY}$# ${NC}"
+                        exit 1
+                    fi
                 popd &> /dev/null
                 tar -cf "build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}".tar.gz" "build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}"" 
             }; echo
             for((i=0; i < $#; i++)){
                 Package="build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}""
                 pushd "$Package" &> /dev/null
+                    echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Building${WHITE} >>> ${PKGNAME[$i]}${NC}"
                     source ./MOONBUILD build
+                    echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Installing${WHITE} >>> ${PKGNAME[$i]}${NC}"
                     source ./MOONBUILD install
                 popd &> /dev/null
+                echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Completed the build${WHITE} >>> ${PACKAGENAME[$i]}${NC}"
             }
             popd &> /dev/null
         fi
@@ -348,7 +383,6 @@ case $1 in
             exit 1
         fi
         play_animation "${YELLOW}Activity: ${WHITE}Checking if packages exist${NC}"
-        sleep 0.1
         for PACKAGE in "$@"; do
             if [ ! -d "/var/db/Veiler/sync/$PACKAGE" ]; then echo -e "${ORANGE}\nError: ${WHITE}The requested package ${YELLOW}$PACKAGE${WHITE} could not be found on the database.${NC}"; veiler_stop_animation; exit 1; fi
         done
@@ -372,19 +406,24 @@ case $1 in
                     fi
                 fi
             }
-            play_animation "${YELLOW}Important: ${WHITE}Extracting the package build tarballs${NC}"
+            echo -e "${YELLOW}Important: ${WHITE}Extracting the build tarballs${NC}"
             for((i=0; i < $#; i++)){
+            echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Extracting >>> ${WHITE}${PKGNAME[$i]}${NC}"
                 tar xf "build-${PKGNAME[$i]}-${PKGVERSION[$i]}.tar.gz"
                 if [ $? -ne 0 ]; then
-                    veiler_stop_animation
-                    echo -e "${ORANGE}Error: ${WHITE}Could not extract the build tarball for ${PKGNAME[$i]}"; exit 1
+                    echo -e "${ORANGE}Error: ${WHITE}Could not extract the build tarball for ${PKGNAME[$i]} ${GRAY} ($((i+1))/$#)${NC}"; exit 1
                 fi
             }
-            veiler_stop_animation
             for((i=0; i < $#; i++)){
+                echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Uninstalling ${WHITE}>>> ${PKGNAME[$i]}${NC}"
                 pushd "build-${PKGNAME[$i]}-${PKGVERSION[$i]}" &> /dev/null
                     source ./MOONBUILD uninstall
+                    if [ $? -ne 0 ]; then
+                        echo -e "${ORANGE}Error: ${WHITE}Failed to uninstall ${PKGNAME[$i]} ${GRAY}($((i+1))/$#)${NC}"
+                        exit 1
+                    fi
                 popd &> /dev/null
+                echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Successfully uninstalled ${WHITE}>>> ${PKGNAME[$i]}${NC}"
             }
             popd &> /dev/null
         else    
@@ -401,21 +440,26 @@ case $1 in
                     fi
                 fi
             }
+            echo -e "${YELLOW}Important: ${WHITE}Extracting the build tarballs...${NC}"
             for((i=0; i < $#; i++)){
+                echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Extracting >>> ${WHITE}${PKGNAME[$i]}${NC}"
                 tar xf "build-${PKGNAME[$i]}-${PKGVERSION[$i]}.tar.gz"
                 if [ $? -ne 0 ]; then
-                    veiler_stop_animation
-                    echo -e "${ORANGE}Error: ${WHITE}Could not extract the build tarball for ${PKGNAME[$i]}"; exit 1
+                    echo -e "${ORANGE}Error: ${WHITE}Could not extract the build tarball for ${PKGNAME[$i]}${NC}"; exit 1
                 fi
             }
-            veiler_stop_animation
             for((i=0; i < $#; i++)){
+                echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Uninstalling ${WHITE}>>> ${PKGNAME[$i]}${NC}"
                 pushd "build-${PKGNAME[$i]}-${PKGVERSION[$i]}" &> /dev/null
                     source ./MOONBUILD uninstall
+                    if [ $? -ne 0 ]; then
+                        echo -e "${ORANGE}Error: ${WHITE}Failed to uninstall ${PKGNAME[$i]} ${GRAY}($((i+1))/$#)${NC}"
+                        exit 1
+                    fi
                 popd &> /dev/null
+                echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Successfully uninstalled ${WHITE}>>> ${PKGNAME[$i]}${NC}"
             }
             popd &> /dev/null
-
         fi
 	;;
 	strengthen)
@@ -574,22 +618,22 @@ case $1 in
         if [ $(id -u) -ne 0 ]; then
             echo -e "${YELLOW}Notice: ${WHITE}You have to become root in order to perform this action.${NC}"
             exit 1
-        elif [ ! -z "$3" ]; then
-            echo -e "${ORANGE}Error: ${WHITE}Only one package may be provided at a time${NC}"
-            exit 1
         elif [ -z "$2" ]; then
             echo -e "${ORANGE}Error: ${WHITE}No package was provided!${NC}"
             exit 1
         fi
-        PACKAGES=$(find /var/cache/Veiler -name "build-"$2"-*.*")
-        if [ -z "$PACKAGES" ]; then
-            echo -e "${ORANGE}Error: ${WHITE}No occurences of the following package could be found${NC}"
+        PACKAGES=()
+        for((i=1; i <= $#; i++)){
+            PACKAGES[$((i-1))]=$(find /var/cache/Veiler -name "build-"${!i}"-*.*")
+        }
+        if [ -z "${PACKAGES[@]}" ]; then
+            echo -e "${ORANGE}Error: ${WHITE}No occurences of the following packages could be found${NC}"
             exit 1
         fi
         echo -e "${YELLOW}Notice: ${WHITE}The following occurences were found: ${NC}"
-        echo $PACKAGES
+        echo ${PACKAGES[@]}
         if [ $VEILERASK -eq 1 ]; then
-            echo -ne "${YELLOW}Important: ${WHITE}Are you sure you would like to delete them?[y/n]: ${NC}"
+            echo -ne "${YELLOW}Important: ${WHITE}Are you sure you would like to ${ORANGE}delete${WHITE} them?[y/n]: ${NC}"
             read -n 1
             if [ "$REPLY" == "y" ]; then
                 true; echo
@@ -597,13 +641,13 @@ case $1 in
                 echo; exit 0
             fi
         fi
-        trap 'echo -e "${ORANGE}Error: ${WHITE}Could not delete one or more occurences${NC}"; exit 1'
+        trap 'echo -e "${ORANGE}Error: ${WHITE}Could not delete one or more occurences${NC}"; exit 1' ERR
         if [ $VEILERQUIET -eq 1 ]; then
             rm -rf $PACKAGES
         else
             rm -rfv $PACKAGES
         fi
-        echo -e "${YELLOW}Notice: ${WHITE}Successfully deleted all the occurences for $1${NC}"
+        echo -e "${YELLOW}Notice: ${WHITE}Successfully deleted all the occurences for: $@${NC}"
     ;;
 	*)
         if [ -z $1 ]; 
