Added the usage of db for uninstallation of packages, and an info option

diff --git a/Veiler b/Veiler
--- a/Veiler
+++ b/Veiler
@@ -38,6 +38,14 @@ package_check(){
 clean(){
     rm -rvf /var/cache/Veiler/*
 }
+uninstalldb(){
+    LINENUMBER="$(cat -n /var/db/Veiler/package.db | grep $1 | awk '{print $1}')"
+    sed -i "${LINENUMBER} s@yes@no@" /var/db/Veiler/package.db
+}
+installdb(){
+    LINENUMBER="$(cat -n /var/db/Veiler/package.db | grep $1 | awk '{print $1}')"
+    sed -i "${LINENUMBER} s@no@yes@" /var/db/Veiler/package.db
+}
 for(( i=1; i <= $#; i++ )){
     case ${!i} in
         --quiet)
@@ -77,7 +85,6 @@ case $1 in
             exit 1
         fi
         shift 
-        echo -e "${WHITE}Packages to be installed: $@${NC}"
         if [ $VEILERQUIET -eq 0 ]; then
             if [ $# -ge 2 ]; then
                 VEILERARGS=$@
@@ -127,8 +134,10 @@ case $1 in
                         pushd $1
                             source ./MOONBUILD chkdeps
                             source ./MOONBUILD build
-                            trap 'echo -e "${YELLOW}An error was encountered while building $1. Not installing $1${NC}"; exit 1' ERR
-                            source ./MOONBUILD install
+                            source ./MOONBUILD install 
+                            installdb $1
+                            VERLINE="$(cat -n /var/db/Veiler/package.db | grep $1 | awk '{print $1}')"
+                            sed -i "${VERLINE} s@0@${MOONPKGVERSION}@" /var/db/Veiler/package.db
                             trap - ERR
                         popd
                     ;;
@@ -188,6 +197,9 @@ case $1 in
                             source ./MOONBUILD chkdeps
 			    	        source ./MOONBUILD build
                             source ./MOONBUILD install
+                            installdb $1
+                            VERLINE="$(cat -n /var/db/Veiler/package.db | grep $1 | awk '{print $1}')"
+                            sed -i "${VERLINE} s@0@${MOONPKGVERSION}@" /var/db/Veiler/package.db
 			            popd &> /dev/null
                         rm -rf "$1"; rm -f "$1.tar.gz" "$1.tar.gz.*"
 				    ;;
@@ -239,9 +251,15 @@ case $1 in
 		        case $? in
 		            8)
 				        echo -e "${YELLOW}Package ${WHITE}$1${WHITE}does not exist!${NC}"
+                        kill $PROCESSID
 		    	    ;;
                     0)
                     echo -e "\n${ORANGE}Package ${WHITE}$1${WHITE} found!${NC}"
+                    echo -e "${YELLOW}Checking if its already uninstalled...${NC}"
+                    if [ $(cat /var/db/Veiler/package.db | grep $1 | awk '{print $2}') == "no" ]; then
+                        echo -e "${WHITE}The package ${YELLOW}$1${WHITE} is already uninstalled.${NC}"
+                        exit 1
+                    fi
 			        echo -e "${YELLOW}Uninstalling ${WHITE}$1${YELLOW} in${NC}"
 			        for i in 1 2 3 4 5 ; do
                         printf "${WHITE}%d${NC}" "$i"
@@ -260,8 +278,10 @@ case $1 in
                     done &
                     PROCESSID=$!
                     tar xf "$1.tar.gz" && kill $PROCESSID && echo -e "\n${YELLOW}->Successfully extracted $1.tar.gz${NC}"
+                    if [ $? -ne 0 ]; then echo -e "${ORANGE}An error was encountered while extracting!${NC}"; kill $PROCESSID; exit 1; fi
 					pushd "$1" &> /dev/null
 				        source ./MOONBUILD uninstall
+                        uninstalldb $1
 				    popd &> /dev/null
 			        ;;
                     *)
@@ -289,6 +309,10 @@ case $1 in
                     ;;                    
                     0)
                         echo -e "\n${ORANGE}Package ${WHITE}$1${WHITE} found!${NC}"
+                        if [ $(cat /var/db/Veiler/package.db | grep $1 | awk '{print $2}') == "no" ]; then
+                            echo -e "${WHITE}The package ${YELLOW}$1${WHITE} is already uninstalled.${NC}"
+                            exit 1
+                        fi
     			        echo -e "${YELLOW}Uninstalling ${WHITE}$1${YELLOW} in${NC}"
 	    		        for i in 1 2 3 4 5 ; do
                             printf "${WHITE}%d${NC}" "$i"
@@ -301,8 +325,10 @@ case $1 in
                         echo
                         printf "${YELLOW}Extracting the build tarball now...${NC}"
                         tar xvf "$1.tar.gz"
+                        if [ $? -ne 0 ]; then echo -e "${ORANGE}An error was encountered while extracting!${NC}"; exit 1; fi
                         pushd "$1"
                             source ./MOONBUILD uninstall
+                            uninstalldb $1
                         popd
                     ;;
                     *)
@@ -316,6 +342,17 @@ case $1 in
         # TO DO: Later, add a feature to update packages installed on system if new version has been released and is greater than installed version
         xx
 	;;
+    info)
+        if [ -z $2 ]; then
+            echo -e "${YELLOW}No package provided.${NC}"
+        fi
+        OUT="$(sudo cat /var/db/Veiler/package.db | grep $2 | head -n1 | tail -n1)"
+        if [ -z "$OUT" ]; then
+            echo -e "${WHITE}Package ${YELLOW}$2 ${WHITE}does not exist!${NC}"
+        else
+            echo -e "${WHITE}$OUT${NC}"
+        fi
+    ;;
 	help)
 		echo -e "${WHITE}$0 Usage: $0 <OPTIONS> <COMMAND>${NC}"
 		echo -e "${WHITE}$0 unveil|veil <OPTIONS> [PACKAGE]${NC}"
@@ -329,10 +366,11 @@ case $1 in
 		echo -e "${WHITE}$0 strengthen: Updates all packages installed on the system${NC}"
 		echo -e "${WHITE}$0 help: Displays this output${NC}"
         echo -e "${WHITE}$0 version: Display package manager version"
+        echo -e "${WHITE}$0 info: Display information about a package"
 		
 	;;
     version)
-            echo -e "Veiler development version. V"
+            echo -e "Veiler development version. r0-1"
     ;;
 	*)
         echo -e "${WHITE}Invalid action ${YELLOW}$1${WHITE} specified!${NC}"
