Updated database and package manager

diff --git a/Veiler b/Veiler
--- a/Veiler
+++ b/Veiler
@@ -2,7 +2,7 @@
 # Main package manager related variables
 declare -a OPTIONS PACKAGES
 PKGREPO="https://ilovetrees242.github.io/DevHelp/Website/Packages"
-# Soon there will be a feature to use multiple features. altrough not yet
+# Soon there will be a feature to use multiple repos. altrough not yet
 VEILERTESTS=0
 VEILERQUIET=0
 VEILERDOC=0
@@ -13,6 +13,7 @@ VEILERNOROOT=0
 VEILERSKIPDEPS=0
 VEILERSKIPCLEAN=0
 VEILERSKIPINST=0
+VEILERMBE=0
 VEILERDEST="/"
 VEILERCACHEPATH="/var/cache/Veiler/"
 VEILERDBPATH="/var/db/Veiler"
@@ -182,34 +183,30 @@ buildPackages(){
     for((i=0; i < ${#PKGNAME[@]}; i++)){
         echo -e "${GRAY}($((i+1))/${#PKGNAME[@]})${WHITE} Building ${BLUE}>>> ${WHITE}${PKGNAME[$i]}${NC}"
         pushd "build-${PKGNAME[$i]}-${PKGVERSION[$i]}" &> /dev/null
+            trap 'log_err "${GRAY}($((i+1))/${#PKGNAME[@]})${WHITE} Failed to build the package ${RED}>>> ${WHITE}${PKGNAME[$i]}"' ERR
             source ./MOONBUILD build
-            if [ $? -ne 0 ]; then
-                log_err "${GRAY}($((i+1))/${#PKGNAME[@]})${WHITE} Failed to build the package ${RED}>>> ${WHITE}${PKGNAME[$i]}"
-            fi
             if [ $VEILERONLYBUILD -eq 0 ]; then 
+                trap 'log_err "${GRAY}($((i+1))/${#PKGNAME[@]})${WHITE} Failed to install the package ${RED}>>> ${WHITE}${PKGNAME[$i]}"' ERR
                 echo -e "${GRAY}($((i+1))/${#PKGNAME[@]})${WHITE} Installing ${YELLOW}>>> ${WHITE}${PKGNAME[$i]}${NC}"
                 DESTDIR=$VEILERDEST source ./MOONBUILD install
-                if [ $? -ne 0 ]; then
-                    log_err "${GRAY}($((i+1))/${#PKGNAME[@]})${WHITE} Failed to install the package ${RED}>>> ${WHITE}${PKGNAME[$i]}"
-                fi
                 cp -r $VEILERDBPATH/sync/${PKGNAME[$i]} $VEILERDBPATH/local
             fi
         popd &> /dev/null
         echo -e "${GRAY}($((i+1))/${#PKGNAME[@]}) ${WHITE}Completed the build${DARBKLUE} >>> ${WHITE}${PKGNAME[$i]}${NC}"
     }
+    trap - ERR
 }
 uninstallPackages(){
     log_info imp "Uninstalling the package(s)"
     for((i=0; i < ${#PKGNAME[@]}; i++)){
         echo -e "${GRAY}($((i+1))/${#PKGNAME[@]}) ${WHITE}Uninstalling ${BLUE}>>> ${WHITE}${PKGNAME[$i]}${NC}"
         pushd "build-${PKGNAME[$i]}-${PKGVERSION[$i]}" &> /dev/null
+        trap 'log_err "${GRAY}($((i+1))/${#PKGNAME[@]})${WHITE} Failed to uninstall ${RED}>>>${WHITE} ${PKGNAME[$i]}"' ERR
         source ./MOONBUILD uninstall
-        if [ $? -ne 0 ]; then
-            log_err "${GRAY}($((i+1))/${#PKGNAME[@]})${WHITE} Failed to uninstall ${RED}>>>${WHITE} ${PKGNAME[$i]}"
-        fi
         popd &> /dev/null
         echo -e "${GRAY}($((i+1))/${#PKGNAME[@]}) ${WHITE}Successfully uninstalled ${DARKBLUE}>>> ${WHITE}${PKGNAME[$i]}${NC}"
     }
+    trap - ERR
 }
 makepkgarray(){
     PKGVERSION=()
@@ -255,6 +252,7 @@ while [ $# -gt 0 ]; do
     esac
     shift
 done
+# -- Parse options --
 for((i=0; i < ${#OPTIONS[@]}; i++)){
     case ${OPTIONS[$i]} in
         --quiet)
@@ -290,11 +288,15 @@ for((i=0; i < ${#OPTIONS[@]}; i++)){
         --skip-installed)
             if [ $VEILERSKIPINST -eq 0 ]; then VEILERSKIPINST=1; else log_err "Skipping installed packages already enabled!"; fi
         ;;
+        --megabytes)
+            if [ $VEILERMBE -eq 0 ]; then VEILERMBE=1; else log_err "Showing size in megabytes already enabled!"; fi
+        ;;
         *)
             log_err "Invalid option ${GRAY}${OPTIONS[$i]}${NC}"
         ;;
     esac    
 }
+# -- End option parsing --
 if [ $VEILERSKIPINST -eq 1 ]; then
     set -- $(checkIfAlreadyInstalled ${ARGUMENTS[@]})
 else
@@ -331,7 +333,7 @@ case $1 in
             if [ ! -d "$VEILERDBPATH/sync/$PACKAGE" ]; then veiler_stop_animation ; log_err "The requested package ${YELLOW}$PACKAGE${WHITE} could not be found on the database"; fi
         done
         veiler_stop_animation
-        makepkgarray $@
+        # --- Start dependency parsing --
         if [ $VEILERSKIPDEPS -eq 0 ]; then
             second_animation "$(log_info imp "Calculating dependencies")"
             PKGCOUNT=0 
@@ -407,6 +409,8 @@ case $1 in
             set -- ${PACKAGES[@]}
             veiler_stop_animation
         fi
+        # -- End dependency calculating --
+        makepkgarray $@
         echo -ne "\n${YELLOW}Packages to be installed: ${NC}"
         for((i=0; i < $#; i++)){
             if [ -d $VEILERDBPATH/local/"${PKGNAME[$i]}" -a -n "${PKGNAME[$i]}" ]; then
@@ -426,34 +430,54 @@ case $1 in
             SPACEBUFFER="$(echo $SPACEBUFFER | sed 's/"//g')"
             ((TOTALDSR+=SPACEBUFFER))
         done
-        ((TOTALDSR/=1024))
-        echo -e "${DARKBLUE}*** ${BLUE}Total disk space required: ${WHITE}"$TOTALDSR"KiB${NC}"
+        if [ $VEILERMBE -eq 1 ]; then
+            ((TOTALDSR=TOTALDSR/1024/1024))
+            echo -e "${DARKBLUE}*** ${BLUE}Total disk space required: ${WHITE}"$TOTALDSR"MiB${NC}"
+        else
+            ((TOTALDSR/=1024))
+            echo -e "${DARKBLUE}*** ${BLUE}Total disk space required: ${WHITE}"$TOTALDSR"KiB${NC}"
+        fi
         for PACKAGE in $@; do
             SPACEBUFFER=$(sed -n 's/^DOWNLOADSIZE=//p' $VEILERDBPATH/sync/$PACKAGE/info)
             SPACEBUFFER="$(echo $SPACEBUFFER | sed 's/"//g')"
             ((TOTALDOWNLOADSIZE+=SPACEBUFFER))
         done
-        ((TOTALDOWNLOADSIZE/=1024))
-        echo -e "${DARKBLUE}*** ${BLUE}Total download size: ${WHITE}"$TOTALDOWNLOADSIZE"KiB${NC}"
+        if [ $VEILERMBE -eq 1 ]; then
+            ((TOTALDOWNLOADSIZE=TOTALDOWNLOADSIZE/1024/1024))
+            echo -e "${DARKBLUE}*** ${BLUE}Total download size: ${WHITE}"$TOTALDOWNLOADSIZE"MiB${NC}"
+        else
+            ((TOTALDOWNLOADSIZE/=1024))
+            echo -e "${DARKBLUE}*** ${BLUE}Total download size: ${WHITE}"$TOTALDOWNLOADSIZE"KiB${NC}"
+        fi
         for PACKAGE in $@; do
             SPACEBUFFER=$(sed -n 's/^INSTALLEDSIZE=//p' $VEILERDBPATH/sync/$PACKAGE/info)
             SPACEBUFFER="$(echo $SPACEBUFFER | sed 's/"//g')"
             ((TOTALINSTSIZE+=SPACEBUFFER))
         done
-        ((TOTALINSTSIZE/=1024))
-        echo -e "${DARKBLUE}*** ${BLUE}Total installed size: ${WHITE}"$TOTALINSTSIZE"KiB${NC}"
+        if [ $VEILERMBE -eq 1 ]; then
+            ((TOTALINSTSIZE=TOTALINSTSIZE/1024/1024))
+            echo -e "${DARKBLUE}*** ${BLUE}Total installed size: ${WHITE}"$TOTALINSTSIZE"MiB${NC}"
+        else
+            ((TOTALINSTSIZE/=1024))
+            echo -e "${DARKBLUE}*** ${BLUE}Total installed size: ${WHITE}"$TOTALINSTSIZE"KiB${NC}"
+        fi
         for PACKAGE in $@; do
             SPACEBUFFER=$(sed -n 's/^WODOCINSTALLEDSIZE=//p' $VEILERDBPATH/sync/$PACKAGE/info)
             SPACEBUFFER="$(echo $SPACEBUFFER | sed 's/"//g')"
             ((WODOCINSTSIZE+=SPACEBUFFER))
         done
-        ((WODOCINSTSIZE/=1024))
-        echo -e "${DARKBLUE}*** ${BLUE}Total installed size ( without documentation ): ${WHITE}"$WODOCINSTSIZE"KiB${NC}"
+        if [ $VEILERMBE -eq 1 ]; then 
+            ((WODOCINSTSIZE=WODOCINSTSIZE/1024/1024))
+            echo -e "${DARKBLUE}*** ${BLUE}Total installed size ( without documentation ): ${WHITE}"$WODOCINSTSIZE"MiB${NC}"
+        else
+            ((WODOCINSTSIZE/=1024))
+            echo -e "${DARKBLUE}*** ${BLUE}Total installed size ( without documentation ): ${WHITE}"$WODOCINSTSIZE"KiB${NC}"
+        fi 
         if [ "$VEILERASK" -eq 1 ]; then
             echo -ne "\n${YELLOW}||| ${WHITE}Proceed with the installation?[y/n]: "
             read -n 1
             if [ "$REPLY" == "y" ]; then
-                echo; true
+                true; echo -e "${NC}"
             else
                 echo -e "\n${WHITE}Goodbye!${NC}"; exit 0
             fi
@@ -493,7 +517,7 @@ case $1 in
             echo -ne "\n\n${BLUE}||| ${WHITE}Proceed with the uninstallation?[y/n]: ${NC}"
             read -n 1
             if [ $REPLY == "y" ]; then
-                true; echo
+                true; echo -e "${NC}"
             else
                 echo -e "\n${WHITE}Goodbye!${NC}"; exit 0
             fi
@@ -540,9 +564,10 @@ case $1 in
 	    echo -e "${GRAY}--documentation${NC}${WHITE} : Enables documentation (this might install extra dependencies)${NC}"
         echo -e "${GRAY}--test${NC}${WHITE}          : Enables test harnesses${NC}" 
         echo -e "${GRAY}--ask${NC}${WHITE}           : Use confirmation prompts${NC}"
-        echo -e "${GRAY}--no-root${NC}${WHITE}       : Don't use superuser priveleges ( might cause errors when installing in priveleged directories )${NC}"
-        echo -e "${GRAY}--skip-clean${NC}${WHITE}    : Skip deleting existing build directories in cache${NC}"
-        echo -e "${GRAY}--skip-clean${NC}${WHITE}    : Skip dependency check ( can break packages )${NC}"
+        echo -e "${GRAY}--no-root${NC}${WHITE}       : Don't use superuser priveledges ( might cause errors when installing in priveleged directories )${NC}"
+        echo -e "${GRAY}--skip-clean${NC}${WHITE}    : Skip deleting existing build directories in cache ( will cause the package manager to not start building from scratch${NC}"
+        echo -e "${GRAY}--skip-deps${NC}${WHITE}     : Skip dependency check ( can break packages )${NC}"
+        echo -e "${GRAY}--megabytes${NC}${WHITE}     : Show size in megabytes instead of kilobytes${NC}"
 		echo -e "${WHITE}unveil     : Installs a package from source.${NC}"
         echo -e "${WHITE}   -> ${GRAY}--with-dest <DESTDIR> ${WHITE}: Installs package into <DESTDIR> instead of default /${NC}"
         echo -e "${WHITE}   -> ${GRAY}--build-only          ${WHITE}: This option makes the package manager only compile and build the package and skip installing it.${NC}"
@@ -563,7 +588,7 @@ case $1 in
             echo " \ \/ /  | ----| | | | |_  | ----|  | |    "
             echo "  \__/   |_____  |_| |___| |_____   |_|    "
             echo -e "${NC}"
-            echo -e "${YELLOW}Veiler ${WHITE}development version 1.3.2${NC}"
+            echo -e "${YELLOW}Veiler ${WHITE}development version 1.3.3${NC}"
     ;;
     search)
         shift
@@ -689,9 +714,9 @@ case $1 in
         trap 'log_err "Could not delete one or more occurences"' ERR
         for((i=0; i < ${#PACKAGES[@]}; i++)){
             if [ $VEILERQUIET -eq 1 ]; then
-                rm -rf "${PACKAGES[$i]}"
+                rm -rf ${PACKAGES[$i]}
             else
-                rm -rfv "${PACKAGES[$i]}"
+                rm -rfv ${PACKAGES[$i]}
             fi
         }
         log_info notice "Successfully deleted all the occurences for: $@"
