Added a new feature

diff --git a/Veiler b/Veiler
--- a/Veiler
+++ b/Veiler
@@ -7,6 +7,10 @@ VEILERQUIET=0
 VEILERDOC=0
 VEILERASK=0
 VEILERSKIPDESC=0
+VEILERDEST="/"
+PROCESSID=""
+
+# Colors
 DARKBLUE='\033[0;34m'
 BLUE='\033[1;34m'
 YELLOW='\033[1;33m'
@@ -15,7 +19,6 @@ WHITE='\033[1;37m'
 GRAY='\033[0;37m'
 DARKGRAY='\033[1;30m'
 NC='\033[0m'
-PROCESSID=""
 
 # Package handling related variables
 PACKAGES=""
@@ -109,6 +112,16 @@ for(( i=1; i <= $#; i++ )){
             elif [ $VEILERSKIPDESC -eq 1 ]; then
                 echo -e "${ORANGE}Error: ${WHITE}Skipping description is already enabled"
             fi
+        ;;
+        --with-dest)
+            ((i++))
+            if [ -z ${!i} ]; then
+                echo -e "${ORANGE}Error: ${GRAY}--with-dest${WHITE} option requires an argument.${NC}"
+                exit 1
+            fi
+            VEILERDEST=${!i}
+            set -- ${@:1:$((i-2))} ${@:$((i+1))}
+            i=0
         ;;
         *)
             OPTBUFFER=${!i}
@@ -264,6 +277,8 @@ case $1 in
             else
                 echo -e "\n${WHITE}Goodbye!${NC}"; exit 0
             fi
+        else
+            echo -e "\n"
         fi
         if [ $VEILERQUIET -eq 0 ]; then
             echo -e "${YELLOW}Notice: ${WHITE}Changing directory to /var/cache/Veiler...${NC}"
@@ -281,7 +296,7 @@ case $1 in
             }
             echo -e "${YELLOW}Important: ${WHITE}Extracting the package build tarballs...${NC}"
             for((i=0; i < $#; i++)){
-                echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Extracting >>> ${WHITE}${PKGNAME[$i]}"
+                echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Extracting ${BLUE}>>> ${WHITE}${PKGNAME[$i]}"
                 tar xf "build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}".tar.gz"
                 if [ $? -ne 0 ]; then
                     echo -e "${ORANGE}Error: ${WHITE}Could not extract the build tarball for ${YELLOW}${PKGNAME[$i]} ${GRAY}($((i+1))/$#) ${NC}"; exit 1
@@ -297,7 +312,7 @@ case $1 in
                 popd &> /dev/null
             }
             for((i=0; i < $#; i++)){
-                echo -ne "\r${WHITE}(${GRAY}"$((i+1))"/"$#"${WHITE}) ${YELLOW}Important: ${WHITE}Verifying package integrity ||| ${PKGNAME[$i]}                                     "
+                echo -ne "\r${WHITE}(${GRAY}"$((i+1))"/"$#"${WHITE}) ${YELLOW}Important: ${WHITE}Verifying package integrity ${DARKBLUE}|||${WHITE} ${PKGNAME[$i]}                                     "
                 pushd "build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}"" &> /dev/null
                     source ./MOONBUILD verifyintegrity
                     if [ $? -ne 0 ]; then
@@ -309,19 +324,19 @@ case $1 in
             }; echo
             for((i=0; i < $#; i++)){
                 Package="build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}""
-                pushd $Package 
-                    echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Building ${WHITE}>>> ${PKGNAME[$i]}${NC}"
+                pushd "$Package" &> /dev/null
+                    echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Building ${ORANGE}>>> ${WHITE}${PKGNAME[$i]}${NC}"
                     source ./MOONBUILD build
                     if [ $? -ne 0 ]; then
-                        echo -e "${ORANGE}Error: ${WHITE}Failed to build >>> ${PKGNAME[$i]}${NC}"; exit 1
+                        echo -e "${ORANGE}Error: ${WHITE}Failed to build ${ORANGE}>>> ${WHITE}${PKGNAME[$i]}${NC}"; exit 1
                     fi
-                    echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Installing ${WHITE}>>> ${PKGNAME[$i]}${NC}"
-                    source ./MOONBUILD install
+                    echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Installing ${GRAY}>>> ${WHITE}${PKGNAME[$i]}${NC}"
+                    DESTDIR=$VEILERDEST source ./MOONBUILD install
                     if [ $? -ne 0 ]; then
-                        echo -e "${ORANGE}Error: ${WHITE}Failed to configure >>> ${PKGNAME[$i]}${NC}"; exit 1
+                        echo -e "${ORANGE}Error: ${WHITE}Failed to install ${GRAY}>>> ${WHITE}${PKGNAME[$i]}${NC}"; exit 1
                     fi
-                popd
-                echo -e "${GRAY}($((i+1))/$#)${YELLOW}Completed build${WHITE} >>> ${PKGNAME[$i]}${NC}"
+                popd &> /dev/null
+                echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Completed build${WHITE} >>> ${PKGNAME[$i]}${NC}"
                 rm -rf $Package
             }
             popd
@@ -341,10 +356,9 @@ case $1 in
             }
             echo -e "${YELLOW}Important: ${WHITE}Extracting the package build tarballs...${NC}"
             for((i=0; i < $#; i++)){
-                echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Extracting >>> ${WHITE}${PKGNAME[$i]}"
+                echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Extracting ${BLUE}>>> ${WHITE}${PKGNAME[$i]}"
                 tar xf "build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}".tar.gz"
                 if [ $? -ne 0 ]; then
-                    veiler_stop_animation
                     echo -e "${ORANGE}Error: ${WHITE}Could not extract the build tarball for ${YELLOW}${PKGNAME[$i]} ${GRAY}($((i+1))/$#)${NC}"; exit 1
                 fi
             }
@@ -358,11 +372,11 @@ case $1 in
                 popd &> /dev/null
             }
             for((i=0; i < $#; i++)){
-                echo -ne "\r${WHITE}(${GRAY}"$((i+1))"/"$#"${WHITE}) ${YELLOW}Important: ${WHITE}Verifying package integrity ||| ${PKGNAME[$i]}                 "
+                echo -ne "\r${WHITE}(${GRAY}"$((i+1))"/"$#"${WHITE}) ${YELLOW}Important: ${WHITE}Verifying package integrity ${DARKBLUE}|||${WHITE} ${PKGNAME[$i]}                 "
                 pushd "build-${PKGNAME[$i]}-${PKGVERSION[$i]}" &> /dev/null 
                     source ./MOONBUILD verifyintegrity
                     if [ $? -ne 0 ]; then
-                        echo -e "${ORANGE}Error: ${WHITE}Failed to verify package integrity for package for ${PKGNAME[$i]} ${GRAY}$((i+1)) ${WHITE}of ${GRAY}$# ${NC}"
+                        echo -e "${ORANGE}Error: ${WHITE}Failed to verify package integrity for package for ${PKGNAME[$i]} ${GRAY}($((i+1))/$#)${NC}"
                         exit 1
                     fi
                 popd &> /dev/null
@@ -371,15 +385,15 @@ case $1 in
             for((i=0; i < $#; i++)){
                 Package="build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}""
                 pushd "$Package" &> /dev/null
-                    echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Building${WHITE} >>> ${PKGNAME[$i]}${NC}"
+                    echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Building${WHITE} ${ORANGE}>>> ${WHITE}${PKGNAME[$i]}${NC}"
                     source ./MOONBUILD build
                     if [ $? -ne 0 ]; then
-                        echo -e "${ORANGE}Error: ${WHITE}Failed to build >>> ${PKGNAME[$i]}${NC}"; exit 1
+                        echo -e "${ORANGE}Error: ${WHITE}Failed to build ${ORANGE}>>> ${WHITE}${PKGNAME[$i]}${NC}"; exit 1
                     fi
-                    echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Installing${WHITE} >>> ${PKGNAME[$i]}${NC}"
-                    source ./MOONBUILD install
+                    echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Installing ${GRAY}>>> ${WHITE}${PKGNAME[$i]}${NC}"
+                    DESTDIR=$VEILERDEST source ./MOONBUILD install
                     if [ $? -ne 0 ]; then
-                        echo -e "${ORANGE}Error: ${WHITE}Failed to configure >>> ${PKGNAME[$i]}${NC}"; exit 1
+                        echo -e "${ORANGE}Error: ${WHITE}Failed to configure ${GRAY}>>> ${WHITE}${PKGNAME[$i]}${NC}"; exit 1
                     fi
                 popd &> /dev/null
                 echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Completed the build${WHITE} >>> ${PKGNAME[$i]}${NC}"
@@ -409,13 +423,15 @@ case $1 in
             echo -ne "${WHITE}${PKGNAME[$i]} ${GRAY}(${PKGVERSION[$i]})${NC}   "
         }
         if [ $VEILERASK -eq 1 ]; then
-            echo -ne "\n${BLUE}|||${WHITE}Proceed with the uninstallation?[y/n]: ${NC}"
+            echo -ne "\n\n${BLUE}||| ${WHITE}Proceed with the uninstallation?[y/n]: ${NC}"
             read -n 1
             if [ $REPLY == "y" ]; then
                 true; echo
             else
                 echo -e "\n${WHITE}Goodbye!${NC}"; exit 0
             fi
+        else 
+            echo -e "\n"
         fi
         if [ "$VEILERQUIET" -eq 1 ]; then
             echo -e "${YELLOW}Notice: ${WHITE}Changing directory to /var/cache/Veiler...${NC}"
@@ -433,14 +449,14 @@ case $1 in
             }
             echo -e "${YELLOW}Important: ${WHITE}Extracting the build tarballs${NC}"
             for((i=0; i < $#; i++)){
-            echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Extracting >>> ${WHITE}${PKGNAME[$i]}${NC}"
+            echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Extracting ${BLUE}>>> ${WHITE}${PKGNAME[$i]}${NC}"
                 tar xf "build-${PKGNAME[$i]}-${PKGVERSION[$i]}.tar.gz"
                 if [ $? -ne 0 ]; then
                     echo -e "${ORANGE}Error: ${WHITE}Could not extract the build tarball for ${PKGNAME[$i]} ${GRAY} ($((i+1))/$#)${NC}"; exit 1
                 fi
             }
             for((i=0; i < $#; i++)){
-                echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Uninstalling ${WHITE}>>> ${PKGNAME[$i]}${NC}"
+                echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Uninstalling ${DARKBLUE}>>> ${WHITE}${PKGNAME[$i]}${NC}"
                 pushd "build-${PKGNAME[$i]}-${PKGVERSION[$i]}" &> /dev/null
                     source ./MOONBUILD uninstall
                     if [ $? -ne 0 ]; then
@@ -448,7 +464,7 @@ case $1 in
                         exit 1
                     fi
                 popd &> /dev/null
-                echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Successfully uninstalled ${WHITE}>>> ${PKGNAME[$i]}${NC}"
+                echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Successfully uninstalled ${BLUE}>>> ${WHITE}${PKGNAME[$i]}${NC}"
             }
             popd &> /dev/null
         else    
@@ -467,14 +483,14 @@ case $1 in
             }
             echo -e "${YELLOW}Important: ${WHITE}Extracting the build tarballs...${NC}"
             for((i=0; i < $#; i++)){
-                echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Extracting >>> ${WHITE}${PKGNAME[$i]}${NC}"
+                echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Extracting ${BLUE}>>> ${WHITE}${PKGNAME[$i]}${NC}"
                 tar xf "build-${PKGNAME[$i]}-${PKGVERSION[$i]}.tar.gz"
                 if [ $? -ne 0 ]; then
                     echo -e "${ORANGE}Error: ${WHITE}Could not extract the build tarball for ${PKGNAME[$i]}${NC}"; exit 1
                 fi
             }
             for((i=0; i < $#; i++)){
-                echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Uninstalling ${WHITE}>>> ${PKGNAME[$i]}${NC}"
+                echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Uninstalling ${DARKBLUE}>>> ${WHITE}${PKGNAME[$i]}${NC}"
                 pushd "build-${PKGNAME[$i]}-${PKGVERSION[$i]}" &> /dev/null
                     source ./MOONBUILD uninstall
                     if [ $? -ne 0 ]; then
@@ -482,7 +498,7 @@ case $1 in
                         exit 1
                     fi
                 popd &> /dev/null
-                echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Successfully uninstalled ${WHITE}>>> ${PKGNAME[$i]}${NC}"
+                echo -e "${GRAY}($((i+1))/$#) ${YELLOW}Successfully uninstalled ${BLUE}>>> ${WHITE}${PKGNAME[$i]}${NC}"
             }
             popd &> /dev/null
         fi
@@ -519,6 +535,7 @@ case $1 in
         echo -e "${GRAY}--test${NC}${WHITE}          : Enables test harnesses${NC}" 
         echo -e "${GRAY}--ask${NC}${WHITE}           : Use confirmation prompts{NC}"
 		echo -e "${WHITE}unveil     : Installs a package from source.${NC}"
+        echo -e "${WHITE}   -> ${GRAY}--with-dest <DESTDIR>: Installs package into <DESTDIR> instead of default /"
 		echo -e "${WHITE}veil       : Uninstalls a package installed on the system${NC}"
 		echo -e "${WHITE}strengthen : Updates all packages installed on the system${NC}"
 		echo -e "${WHITE}search     : Matches regex with a package name in the package database${NC}"
@@ -536,7 +553,7 @@ case $1 in
             echo " \ \/ /  | ----| | | | |_  | ----|  | |    "
             echo "  \__/   |_____  |_| |___| |_____   |_|    "
             echo -e "${NC}"
-            echo -e "${WHITE}Veiler pre-release version. ${GRAY}v1.1.3${NC}"
+            echo -e "${WHITE}${YELLOW}Veiler${NC} version 1.2.3${NC}"
     ;;
     search)
         shift
@@ -634,10 +651,11 @@ case $1 in
         fi
     ;;
     rmpkg)
+        shift
         if [ $(id -u) -ne 0 ]; then
             echo -e "${YELLOW}Notice: ${WHITE}You have to become root in order to perform this action.${NC}"
             exit 1
-        elif [ -z "$2" ]; then
+        elif [ -z "$1" ]; then
             echo -e "${ORANGE}Error: ${WHITE}No package was provided!${NC}"
             exit 1
         fi
@@ -645,7 +663,7 @@ case $1 in
         for((i=1; i <= $#; i++)){
             PACKAGES[$((i-1))]=$(find /var/cache/Veiler -name "build-"${!i}"-*.*")
         }
-        if [ -z "${PACKAGES[@]}" ]; then
+        if [ -z "${PACKAGES[*]}" ]; then
             echo -e "${ORANGE}Error: ${WHITE}No occurences of the following packages could be found${NC}"
             exit 1
         fi
@@ -661,11 +679,13 @@ case $1 in
             fi
         fi
         trap 'echo -e "${ORANGE}Error: ${WHITE}Could not delete one or more occurences${NC}"; exit 1' ERR
-        if [ $VEILERQUIET -eq 1 ]; then
-            rm -rf $PACKAGES
-        else
-            rm -rfv $PACKAGES
-        fi
+        for((i=0; i < ${#PACKAGES[@]}; i++)){
+            if [ $VEILERQUIET -eq 1 ]; then
+                rm -rf ${PACKAGE[$i]}
+            else
+                rm -rfv ${PACKAGE[$i]}
+            fi
+        }
         echo -e "${YELLOW}Notice: ${WHITE}Successfully deleted all the occurences for: $@${NC}"
     ;;
 	*)
